import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='main'>
                <div id='header'>

                </div>
                <div id='content'>
                    <div className='lets-button'>
                        🐣 Let's 🐣
                    </div>
                    <img src='/main.png' alt='logo'></img>
                </div>
                <div id='footer'>
                    <p>with</p>
                    <span>jrontend</span>
                </div>
            </div>
        </>
    )
}
